---
- name: Install Tomcat
  hosts: tomcat_servers
  become: true

  tasks:
  - name: Install Tomcat
    yum:
      name: tomcat
      state: present

  - name: Start Tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
