---
- name: Install Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.52/bin/apache-tomcat-9.0.52.tar.gz
        dest: /tmp/apache-tomcat-9.0.52.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-9.0.52.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Tomcat
      shell: "/opt/apache-tomcat-9.0.52/bin/startup.sh"
      args:
        executable: /bin/bash
