- hosts: tomcat_servers
  become: yes
  tasks:

  - name: Install necessary packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - java-1.8.0-openjdk
      - wget

  - name: Download Tomcat 9
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz
      dest: /tmp/apache-tomcat-9.0.93.tar.gz

  - name: Extract Tomcat 9
    unarchive:
      src: /tmp/apache-tomcat-9.0.93.tar.gz
      dest: /opt/
      remote_src: yes

  - name: Move Tomcat to the correct directory
    command: mv /opt/apache-tomcat-9.0.93 /opt/tomcat9

  - name: Update server.xml to change port to 80
    lineinfile:
      path: /opt/tomcat9/conf/server.xml
      regexp: 'Connector port="8080"'
      line: 'Connector port="80"'
      backup: yes

  - name: Create a systemd service file for Tomcat
    copy:
      dest: /etc/systemd/system/tomcat9.service
      content: |
        [Unit]
        Description=Apache Tomcat 9
        After=network.target

        [Service]
        Type=forking
        ExecStart=/opt/tomcat9/bin/startup.sh
        ExecStop=/opt/tomcat9/bin/shutdown.sh
        User=root
        Group=root

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd to apply the new service
    command: systemctl daemon-reload

  - name: Start Tomcat 9
    service:
      name: tomcat9
      state: started

  - name: Enable Tomcat 9 to start on boot
    service:
      name: tomcat9
      enabled: yes
