---
- name: Start Tomcat 9
  hosts: tomcat_servers
  become: yes
  tasks:

    - name: Start Tomcat service
      service:
        name: tomcat9
        state: started

    - name: Enable Tomcat service on boot
      service:
        name: tomcat9
        enabled: yes
