---
- name: Install Java on Windows Server
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Ensure temp directory exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Find Java installer file on Ansible Tower (Linux)
      find:
        paths: /ansible/projects/JAVA/update
        patterns: "jdk-*.exe"
      register: java_installer
      delegate_to: localhost

    - name: Fail if no Java installer file was found on Ansible Tower
      fail:
        msg: "No Java installer file found in /ansible/projects/JAVA/update"
      when: java_installer.matched == 0

    - name: Copy Java installer to Windows instance
      win_copy:
        src: "{{ java_installer.files[0].path }}"
        dest: "C:\\temp\\{{ java_installer.files[0].path | basename }}"
      when: java_installer.matched > 0

    - name: Install Java
      win_shell: |
        Start-Process -FilePath "C:\\temp\\{{ java_installer.files[0].path | basename }}" -ArgumentList "/s" -Wait
      register: java_install
      when: java_installer.matched > 0

    - name: Set JAVA_HOME environment variable
      win_environment:
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk-{{ java_installer.files[0].path | basename | regex_search('jdk-(.*)-windows-x64.exe') }}"
      when: java_install is succeeded

    - name: Add Java to system PATH
      win_environment:
        name: PATH
        value: "{{ ansible_env.PATH }};C:\\Program Files\\Java\\jdk-{{ java_installer.files[0].path | basename | regex_search('jdk-(.*)-windows-x64.exe') }}\\bin"
        state: present
      when: java_install is succeeded
