---
- name: Check and Install Python and then Install Java
  hosts: windows_servers
  tasks:

    - name: Ensure the temp folder exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Check if Python is installed
      win_command: python --version
      register: python_check
      ignore_errors: true

    - name: Install Python if not found
      win_command: C:\temp\python-3.9.7-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
      when: python_check.rc != 0

    - name: Verify Python installation
      win_command: python --version
      register: python_version_output
      when: python_check.rc != 0

    - name: Display Python version
      debug:
        msg: "{{ python_version_output.stdout }}"
      when: python_check.rc != 0

    - name: Copy Java installer to Windows instance
      win_copy:
        src: /ansible/projects/JAVA/update/jdk-8u401_windows-x64_bin.exe
        dest: C:\temp\jdk-8u401_windows-x64_bin.exe

    - name: Install Java
      win_command: C:\temp\jdk-8u401_windows-x64_bin.exe /s
      register: java_install

    - name: Set JAVA_HOME and update PATH
      win_shell: |
        $env:JAVA_HOME = "C:\Program Files\Java\jdk1.8.0_401"
        [System.Environment]::SetEnvironmentVariable('JAVA_HOME', $env:JAVA_HOME, [System.EnvironmentVariableTarget]::Machine)
        $env:Path += ";$env:JAVA_HOME\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Verify Java installation
      win_command: java -version
      register: java_version_output

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Move Java installer to installed directory
      win_command: |
        Move-Item -Path C:\temp\jdk-8u401_windows-x64_bin.exe -Destination /ansible/projects/JAVA/installed/jdk-8u401_windows-x64_bin.exe
