---
- name: Check and Install Python and then Install Java
  hosts: windows_servers
  tasks:

    - name: Ensure the temp folder exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Copy Python installer to Windows instance
      win_copy:
        src: /ansible/projects/python-installer-3.9.7/python-3.9.7-amd64.exe
        dest: C:\temp\python-3.9.7-amd64.exe

    - name: Check if Python is installed
      win_command: python --version
      register: python_check
      ignore_errors: true

    - name: Install Python if not found
      win_command: C:\temp\python-3.9.7-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
      when: python_check.rc != 0

    - name: Verify Python installation
      win_command: python --version
      register: python_version_output
      when: python_check.rc != 0

    - name: Display Python version
      debug:
        msg: "{{ python_version_output.stdout }}"
      when: python_check.rc != 0

    - name: Copy Java installer to Windows instance
      win_copy:
        src: /ansible/projects/JAVA/update/{{ item }}
        dest: C:\temp\{{ item }}
      with_fileglob:
        - /ansible/projects/JAVA/update/*.exe

    - name: Install Java
      win_command: C:\temp\{{ item }} /s
      register: java_install
      with_fileglob:
        - /ansible/projects/JAVA/update/*.exe

    - name: Detect Java installation path
      win_shell: Get-ChildItem 'C:\Program Files\Java' | Where-Object { $_.PsIsContainer } | Select-Object -ExpandProperty FullName
      register: java_install_path

    - name: Set JAVA_HOME and update PATH dynamically
      win_shell: |
        $env:JAVA_HOME = "{{ java_install_path.stdout }}"
        [System.Environment]::SetEnvironmentVariable('JAVA_HOME', $env:JAVA_HOME, [System.EnvironmentVariableTarget]::Machine)
        $env:Path += ";$env:JAVA_HOME\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Verify Java installation
      win_command: java -version
      register: java_version_output

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Move Java installer to installed directory and keep a copy in update
      win_copy:
        src: C:\temp\{{ item }}
        dest: /ansible/projects/JAVA/installed/{{ item }}
      with_fileglob:
        - /ansible/projects/JAVA/update/*.exe
