---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Find the latest Java installer file on Ansible Tower
      find:
        paths: "/ansible/projects/JAVA/update"
        patterns: "jdk-*.exe"
        recurse: no
      register: java_installer

    - name: Fail if no Java installer file was found on Ansible Tower
      fail:
        msg: "No Java installer file found in /ansible/projects/JAVA/update"
      when: java_installer.matched == 0

    - name: Display the found Java installer file
      debug:
        msg: "Found Java installer: {{ java_installer.files[0].path }}"
      when: java_installer.matched > 0

- hosts: windows_servers
  tasks:
    - name: Copy Java installer to Windows instance
      win_copy:
        src: "{{ hostvars['localhost'].java_installer.files[0].path }}"
        dest: "C:\\temp\\{{ hostvars['localhost'].java_installer.files[0].path | basename }}"
      when: hostvars['localhost'].java_installer.matched > 0

    - name: Install Java
      win_shell: |
        Start-Process -FilePath "C:\\temp\\{{ hostvars['localhost'].java_installer.files[0].path | basename }}" -ArgumentList "/s" -Wait
      when: hostvars['localhost'].java_installer.matched > 0
      register: java_install

    - name: Set JAVA_HOME environment variable
      win_environment:
        state: present
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk1.8.0_411"
      when: java_install is succeeded

    - name: Add Java to system PATH
      win_environment:
        state: present
        name: PATH
        value: "{{ ansible_env.PATH }};C:\\Program Files\\Java\\jdk1.8.0_411\\bin"
      when: java_install is succeeded

    - name: Verify Java installation
      win_shell: "java -version"
      register: java_version
      when: java_install is succeeded

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout }}"
      when: java_install is succeeded
