---
- name: Ensure Java is installed on Windows servers
  hosts: windows_servers
  tasks:

    - name: Ensure the temp folder exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Find Java installer file
      win_find:
        paths: /ansible/projects/JAVA/update
        patterns: 'jdk-*.exe'
      register: java_installer

    - name: Copy Java installer to Windows instance
      win_copy:
        src: /ansible/projects/JAVA/update/{{ java_installer.files[0].path | basename }}
        dest: C:\temp\{{ java_installer.files[0].path | basename }}
      when: java_installer.files | length > 0

    - name: Install Java
      win_shell: |
        $installer = Get-ChildItem -Path C:\temp\jdk-*.exe
        Start-Process -FilePath $installer.FullName -ArgumentList "/s" -Wait
      register: java_install

    - name: Set JAVA_HOME and update PATH
      win_shell: |
        $java_home = Get-ChildItem "C:\Program Files\Java" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        [System.Environment]::SetEnvironmentVariable('JAVA_HOME', $java_home.FullName, [System.EnvironmentVariableTarget]::Machine)
        $env:Path += ";$env:JAVA_HOME\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Verify Java installation
      win_command: java -version
      register: java_version_output

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

- name: Move Java installer on Ansible Controller
  hosts: localhost
  tasks:
    - name: Move Java installer from 'update' to 'installed' on controller
      command: mv /ansible/projects/JAVA/update/{{ java_installer.files[0].path | basename }} /ansible/projects/JAVA/installed/
      when: java_installer.files | length > 0
