---
- name: Ensure Java is installed on Windows servers
  hosts: windows_servers
  tasks:

    - name: Ensure the temp folder exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Copy Java installer to Windows instance
      win_copy:
        src: /ansible/projects/JAVA/update/jdk-*.exe
        dest: C:\temp\jdk-installer.exe

    - name: Install Java
      win_shell: Start-Process -FilePath C:\temp\jdk-installer.exe -ArgumentList "/s" -Wait
      register: java_install

    - name: Set JAVA_HOME and update PATH
      win_shell: |
        $java_home = Get-ChildItem "C:\Program Files\Java" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        [System.Environment]::SetEnvironmentVariable('JAVA_HOME', $java_home.FullName, [System.EnvironmentVariableTarget]::Machine)
        $env:Path += ";$env:JAVA_HOME\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Verify Java installation
      win_command: java -version
      register: java_version_output

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Move Java installer to installed directory
      win_shell: Move-Item -Path C:\temp\jdk-installer.exe -Destination C:\ansible\projects\JAVA\installed\jdk-installer.exe
