---
- name: Manage Java installation on Windows
  hosts: windows_servers
  tasks:
    - name: Ensure the temp folder exists on Windows instance
      win_file:
        path: C:\temp
        state: directory

    - name: Find the Java installer in the update folder
      ansible.builtin.find:
        paths: /ansible/projects/JAVA/update/
        patterns: "*.exe"
      register: java_installer_file

    - name: Fail if no installer file is found
      ansible.builtin.fail:
        msg: "No Java installer file found in the update directory!"
      when: java_installer_file.matched == 0

    - name: Copy Java installer to Windows instance
      win_copy:
        src: "{{ java_installer_file.files[0].path }}"
        dest: C:\temp\{{ java_installer_file.files[0].path | basename }}

    - name: Install Java
      win_command: C:\temp\{{ java_installer_file.files[0].path | basename }} /s

    - name: Verify Java installation
      win_command: java -version
      register: java_version_output

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Move installer file to installed folder
      ansible.builtin.command:
        cmd: mv "{{ java_installer_file.files[0].path }}" /ansible/projects/JAVA/installed/
