---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Find the latest Java installer file on Ansible Tower
      find:
        paths: "/ansible/projects/JAVA/update"
        patterns: "jdk-*.exe"
        recurse: no
      register: java_installer

    - name: Debug to check the files found
      debug:
        var: java_installer.files

    - name: Fail if no Java installer file was found on Ansible Tower
      fail:
        msg: "No Java installer file found in /ansible/projects/JAVA/update"
      when: java_installer.files | length == 0

    - name: Display the found Java installer file
      debug:
        msg: "Found Java installer: {{ java_installer.files[0].path }}"
      when: java_installer.files | length > 0

- hosts: windows_servers
  tasks:
    - name: Copy Java installer to Windows instance
      win_copy:
        src: "{{ hostvars['localhost'].java_installer.files[0].path }}"
        dest: "C:\\temp\\{{ hostvars['localhost'].java_installer.files[0].path | basename }}"
      when: hostvars['localhost'].java_installer.files | length > 0

    - name: Install Java
      win_shell: |
        Start-Process -FilePath "C:\\temp\\{{ hostvars['localhost'].java_installer.files[0].path | basename }}" -ArgumentList "/s" -Wait
      when: hostvars['localhost'].java_installer.files | length > 0
      register: java_install

    - name: Set JAVA_HOME environment variable dynamically
      win_shell: |
        $installedJavaDir = Get-ChildItem -Path "C:\Program Files\Java" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        [Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Program Files\Java\$($installedJavaDir.Name)", "Machine")
      when: java_install is succeeded

    - name: Add Java to system PATH dynamically
      win_shell: |
        $installedJavaDir = Get-ChildItem -Path "C:\Program Files\Java" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        [Environment]::SetEnvironmentVariable("PATH", "$($env:PATH);C:\Program Files\Java\$($installedJavaDir.Name)\bin", "Machine")
      when: java_install is succeeded

    - name: Verify Java installation
      win_shell: "java -version"
      register: java_version
      when: java_install is succeeded

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout }}"
      when: java_install is succeeded
